services:

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    expose: ["3000"]
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - frontend_build:/app/dist
    restart: unless-stopped

  nginx:
    image: nginx:1.29.0-alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  frontend_build:
